/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author invitado
 */
public class VistaAdmin extends javax.swing.JFrame {

    /**
     * Creates new form VistaAdmin
     */
    public VistaAdmin() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCerrar = new javax.swing.JButton();
        jButtonCerrarSesion = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        agregarLibro = new javax.swing.JMenuItem();
        modificarLibro = new javax.swing.JMenuItem();
        eliminarLibro = new javax.swing.JMenuItem();
        consultarLibro = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        agregarOferta = new javax.swing.JMenuItem();
        eliminarOferta = new javax.swing.JMenuItem();
        modificarOferta = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonCerrar.setBackground(new java.awt.Color(44, 7, 55));
        jButtonCerrar.setFont(new java.awt.Font("URW Palladio L", 0, 12)); // NOI18N
        jButtonCerrar.setForeground(new java.awt.Color(254, 254, 254));
        jButtonCerrar.setText("Cerrar");
        jButtonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, -1, 30));

        jButtonCerrarSesion.setBackground(new java.awt.Color(33, 2, 48));
        jButtonCerrarSesion.setFont(new java.awt.Font("URW Palladio L", 0, 12)); // NOI18N
        jButtonCerrarSesion.setForeground(new java.awt.Color(254, 254, 254));
        jButtonCerrarSesion.setText("Cerrar Sesion");
        jButtonCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoApp.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 335));

        jMenu1.setText("Libros");

        agregarLibro.setText("Agregar ");
        agregarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarLibroActionPerformed(evt);
            }
        });
        jMenu1.add(agregarLibro);

        modificarLibro.setText("Modificar ");
        modificarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarLibroActionPerformed(evt);
            }
        });
        jMenu1.add(modificarLibro);

        eliminarLibro.setText("Eliminar");
        eliminarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarLibroActionPerformed(evt);
            }
        });
        jMenu1.add(eliminarLibro);

        consultarLibro.setText("Consultar");
        consultarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarLibroActionPerformed(evt);
            }
        });
        jMenu1.add(consultarLibro);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ofertas");

        agregarOferta.setText("Agregar");
        jMenu2.add(agregarOferta);

        eliminarOferta.setText("Eliminar");
        jMenu2.add(eliminarOferta);

        modificarOferta.setText("Modificar");
        jMenu2.add(modificarOferta);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Usuarios");

        jMenuItem1.setText("Agregar Admin");
        jMenu3.add(jMenuItem1);

        jMenuItem2.setText("Eliminar Admin");
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarLibroActionPerformed
        AgregarLibro a = new AgregarLibro();
        a.setVisible(true);
    }//GEN-LAST:event_agregarLibroActionPerformed

    private void jButtonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonCerrarActionPerformed

    private void jButtonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarSesionActionPerformed
        Interfaz a = new Interfaz();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCerrarSesionActionPerformed

    private void modificarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarLibroActionPerformed
        ModificarLibro a= new ModificarLibro();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_modificarLibroActionPerformed

    private void eliminarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarLibroActionPerformed
        EliminarLibro a= new EliminarLibro();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_eliminarLibroActionPerformed

    private void consultarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarLibroActionPerformed
        ConsultarLibro a = new ConsultarLibro();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_consultarLibroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem agregarLibro;
    private javax.swing.JMenuItem agregarOferta;
    private javax.swing.JMenuItem consultarLibro;
    private javax.swing.JMenuItem eliminarLibro;
    private javax.swing.JMenuItem eliminarOferta;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButtonCerrar;
    private javax.swing.JButton jButtonCerrarSesion;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem modificarLibro;
    private javax.swing.JMenuItem modificarOferta;
    // End of variables declaration//GEN-END:variables
}
